version: "3.8"
services:
  app:
    image: node:latest
    container_name: nodeapp
    environment:
      DB_HOST: mysql1
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: admin
    ports:
      - "3000:3000"
    command: ["bin/bash"]
    volumes:
      - ./:/code
    depends_on:
      - mysql1
    stdin_open: true
    tty: true
  mysql1:
    image: mysql:5.7
    restart: always
    container_name: db1
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"
    volumes:
      - /Users/chaiy/Desktop/353code
    stdin_open: true
    tty: true
volumes:
  db:
    driver: local
