version: "3.9"
services:
  node:
    build: .
    image: node:latest
    container_name: node_container
    environment:
      DB_HOST: mysql1
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: postdb
    ports:
      - "80:3000"
    volumes:
      - C:\Users\chaiy\Desktop\353-project:/dockerapp
    depends_on:
      - mysql1
    stdin_open: true
    tty: true
  react_app:
    build: .
    container_name: react_container
    environment:
      - WATCHPACK_POLLING=true  # Enables React to update on code change
    ports:
      - "8080:8080"
    depends_on:
      - node
      - mysql1
    # command: npm start
    stdin_open: true
    tty: true
  mysql1:
    image: mysql:5.7
    container_name: db_container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    stdin_open: true
    tty: true
volumes: 
  db:
    driver: local
